keys:
	venv/bin/python -m bitcoin_101.keys

create_your_own_network:
	venv/bin/python -m bitcoin_101.create_your_own_network

create_transactions:
	venv/bin/python -m bitcoin_101.create_transactions

deterministic_keys:
	venv/bin/python -m bitcoin_101.deterministic_keys
